name: Hack 1

on:
  push:
    branches:
      - main
      
jobs:
  saludo_main:
    runs-on: ubuntu-latest

    steps:
      - name: Dowload Source
        uses: actions/checkout@v2

      - name: Hola desde Main
        run: echo "¡Hola mundo! Se ha realizado un push a la rama main."
